# In-Class Programming Activity, Day 16
# Jina Park

```{r}
library(ISLR)
```

# The Knots
```{r}
my_knots <- function(x, k) {
  quantile(x, probs=(1:k)/(k+1))
}

my_knots(rnorm(1000), 3)
```

# The Basis Set

Package up the computations to create the model matrix.
```{r}
spline_model_matrix <- function(x, knots) {
  MM <- ccbind(1, x, x^2, x^3)
  for (i in 1:length(knots)) {
    new_vector <- ifelse(x < knots[i], 0, (x-knots[i])^3)
    MM <- cbind(MM, new_vector)
  }
  MM
}
```

```{r}
fit_spline <- function(formula, k=2, data=parent.frame()) {
  #Return a list of items relevant to calculating the value of the spline at any point x.
  y <- eval(formula[[2]], envir=data)
  x <- eval(formula[[3]], envir=data)
  knot_locations <- my_knots(x, k)
  MM <- spline_model_matrix(x, knot_locations)
  mod <- lm(y ~ MM - 1)
  res <- list(coef = coef(mod), knots = knot_locations, cov = vcov(mod))
  resid_df <- length(x) - ncol(MM)
  resid <- mod$residuals
  rse <- sum(resid^2)/resid_df
  class(res) <- "my_spline"
  
  return(res)
}
```

## The predict function
```{r}
predict.my_spline <- function(mod, newx, level = 0.95, intervals=c("none", "confidence", "prediction")) {
  intervals <- match.arg(intervals)
  MM <- spline_model_matrix(newx, mod$knots)
  vals <- MM %*% mod$coef
  se <- sqrt(rowSums(MM %*% mod$cov * MM))
  rse <- mod$rse
  if (intervals == "confidence") return(data.frame(upper = vals + 2*se, vals = vals, lower = vals - 2*se))
  else if (intervals == "prediction") return(data.frame(upper = vals + 2 * sqrt(se^2 + rse^2), vals = vals, lower = vals - 2 * sqrt(se^2 + rse^2)))
  else return(vals)
}
  
```

```{r}
numSeq <- seq(10, 50, length = 100)
spline1 <- fit_spline(wage~age, k=1, data=Wage)
predict(my_spline1, newx = numSeq)
```

Divide wage into training and testing sets. Find the number of knots that minimizes the mean square error on the training set.

```{r}
inds <- sample(1:nrow(Wage), size = nrow(Wage)/2)
trainSet <- Wage[inds, ]
testSet <- Wage[-inds, ]
```

```{r}
# 1 knot
mod <- lm(wage~bs(age, df = 1), data = trainSet)
pred <- predict(mod, testSet)
mean((pred - testSet$age)^2)

# 2 knots
mod2 <- lm(wage~age, df = 5, data = trainSet)
pred2 <- predict(mod2, testSet)
mean((pred2 - testSet$age)^2)

# 5 knots
mod5 <- lm(wage~bs(age, df = 8), data = trainSet)
pred5 <- predict(mod5, testSet)
mean((pred5 - testSet$age)^2)

# 10 knots
mod10 <- lm(wage~bs(age, df = 13), data = trainSet)
pred10 <- predict(mod10, testSet)
mean((pred10 - testSet$age)^2)
```

There should be approximately 1 knot.

## Test statements

```{r}
scoreActivity::score253(16)
```